### PR TITLE
Ibrahim Faruqi

### PR DESCRIPTION
**Pull request by izfaruqi**
LINE ID: ```izfaruqi```

### CODE REVIEW

**Comment by afikrim** [comment]
Thanks for the submission!

Before we check your work, would you kindly tell us what version of Nodejs and npm did you use?

**Comment by izfaruqi** [comment]
Sorry for not including this info, I use Node.js version 14.15.3 and npm version 6.14.10.

**Comment by izfaruqi** [comment]
By any chance, may I add a couple more commits into this pull request?

**Comment by afikrim** [comment]
Thanks for the information.

I cannot answer your question about committing new changes. Just wait for @huf0813 to answer your question.
Thanks

**Comment by izfaruqi** [comment]
Okay, thank you.

**Comment by huf0813** [comment]
> Thanks for the information.
> 
> I cannot answer your question about committing new changes. Just wait for @huf0813 to answer your question.
> Thanks

HI kiki, we are very happy to see your work. 

Well, you don't have to. Please tell us about your work later on interview. Thx

**Comment by izfaruqi** [comment]
Oohh I see, okay then.

**Comment by huf0813** [comment]
You have completed all the instant pass journey. We are about to see your chance here. Any details would be informed by us on private message. Thx and have a good one!

**Comment by izfaruqi** [comment]
I've had lots of fun and new knowledge doing this challenge. Thank you so much for the opportunity :)

**Pull request closed without merging**
